image: node:16.14.2-bullseye

stages:
  - setup
  - test
  - deploy

install:
  stage: setup
  script:
    - npm ci

unit test:
  stage: test
  before_script:
    - apt-get update
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt install -y ./google-chrome*.deb;
    - export CHROME_BIN=/usr/bin/google-chrome
  script:
    - npm ci
    - npm run test -- --no-watch --browsers=ChromeHeadlessCI


deployment:
  stage: deploy
  before_script:
    - npm ci
  script:
    - npx cross-env NG_DEPLOY_AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID NG_DEPLOY_AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY NG_DEPLOY_AWS_BUCKET=profanis-my-first-angular-app NG_DEPLOY_AWS_REGION=eu-central-1 ng deploy
